language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: npm
  email: bleshik@gmail.com
  api_key:
    secure: fhPJ46+76pv72SQRU4d1eSuy+iK4ekeghr4rHSRZRTQbRRvHvP9oORVGViQxueoVgFdKxvNvm4nRfaLxOQRthCb3ZhG8zaI6OB5eSS8lPUfRu1WKYICi/jpl3B8a7JwrzE+Brxo4E+f0zVp7wrt9IzLmdv66YVBCKVQAxpDsi1hqONrDPgxjKnfN2mtbhth5utqcXq90FNDvEUb16YOHZJAd/zxAsAA103jIZ/Vycqk4g2i23bBLazE8LPhz+rTNsCLm3Q9xmlEc24wHsMoGwBRmWPPx7JG5f+ncTxIjrz5QJuI8VzAHLvqD5NJ+tKBPk6K4d4Aad1D5YlmIHHG14awKTvhmpWkwV+ayQPYOeVZ/AJCvKdMUeKFONUWAUWFQOVnOyMW8BZBvn7ukSewLHy+yipWNg4kQ1kzLrOVCs2JeIRhUR4/a/5HkHaDHTbRKbPiezYt8wijdTT7JDsihIQrDXkIxhPHI9cjzTnrMR9Kx8scve/NWSTXtB/yu0tw2qjvYYaSYX92yFHdSxqEGYGI7L3zgI12Wk4JsUkBWm/HiPMO0qRPtP+hTrqUZA9L3YvUakhIBbsSA6gehrCwD7UnTnqCmCpZtufD8aG0pW1Q8pJKBGKSniuKGTPccqJp8knnDqeH1EHhLL8dUYQaCuF2GLQqzB07Bc2G57GM0jCg=
